---
:extensions:
  .md: .html
  .scss: .css
  .rb: .xml
  .erb: .html
:inputs: content
:outputs: output
:serve:
  :port: 8000
:static_files:
  - png
  - gif
  - jpg
  - txt
  - html
:kramdown:
  :template: layout.html.erb
  :auto_id_prefix: '_'
  :syntax_highlighter: rouge
  :syntax_highlighter_opts:
    :line_numbers: false
    :wrap: true
:deploy_to: webfaction:~/webapps/jekyllblog
