# A list of file extensions that nanoc will consider to be textual rather than
# binary. If an item with an extension not in this list is found,  the file
# will be considered as binary.
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]

# The path to the directory where all generated files will be written to. This
# can be an absolute path starting with a slash, but it can also be path
# relative to the site directory.
output_dir: output

# A list of index filenames, i.e. names of files that will be served by a web
# server when a directory is requested. Usually, index files are named
# “index.hml”, but depending on the web server, this may be something else,
# such as “default.htm”. This list is used by nanoc to generate pretty URLs.
index_filenames: [ 'index.html' ]

cache_busting: true

# Configuration of deployment targets using rsync.
deploy:
  default:
    dst: "webfaction:~/webapps/jekyllblog"
    options: ['-glpPrtvz', '--delete']

# Collection of site metadata
site:
  # Tacking code for Google Analytics
  ga_tracking_code: "UA-80284-1"

  # Tracking code for Observer
  observer_tracking_code: "4c9491ee68b726ea7a002ce8"

  # The website title
  title: "Arjan van der Gaag.nl"

  # Default keywords
  keywords: "Arjan van der Gaag, Arjan, van der Gaag, website, AG Webdesign"

  # Default description
  description: 'The personal website of web developer, historian and all-round geek Arjan van der Gaag.'

  # Big tagline on the front page
  tagline: 'I’m <strong>Arjan van der Gaag</strong> and this is my website about me, code, food, photography and more. If you like, we can <a href="mailto:&#x61;&#x72;&#x6A;&#x61;&#x6E;&#x40;&#x61;&#x72;&#x6A;&#x61;&#x6E;&#x76;&#x61;&#x6E;&#x64;&#x65;&#x72;&#x67;&#x61;&#x61;&#x67;&#x2E;&#x6E;&#x6C;">get in touch</a>.'

  # Author name in the meta-tag
  author: Arjan van der Gaag

  # Copyright line in the meta-tag
  copyright: "© copyright 1995–2010 Arjan van der Gaag unless noted otherwise."

# Links to personal profiles on social media websites
elsewhere:
  -
    url: "http://twitter.com/avdgaag"
    title:
    text: "Twitter"
  -
    url: "http://linkedin.com/avdgaag"
    title:
    text: "LinkedIn"
  -
    url: "http://github.com/avdgaag"
    title:
    text: "Github"
  -
    url: "http://flickr.com/photos/arjanvandergaag"
    title:
    text: "Flickr"
  -
    url: "http://delicious.com/arjanvandergaag"
    title:
    text: "Delicious"
  -
    url: "http://last.fm/user/surtur"
    title:
    text: "Last.fm"

# Links to my other sites and pages of interest
other_sites:
  -
    url: "http://border-none.com"
    title: "Practical screencasts to make you a better web developer"
    text: "border:none;"
  -
    url: "http://pasttense.nl/"
    title:
    text: "the Past Tense"
  -
    url: "http://agwebdesign.nl/"
    title:
    text: "AG Webdesign"
  -
    url: "http://yummyinmytummy.nl/"
    title:
    text: "Yummy in my Tummy!"
  -
    url: "http://tumble.arjanvandergaag.nl"
    title:
    text: "My tumblelog"
  -
    url: "http://arjanvandergaag.nl/"
    title:
    text: "Arjan van der Gaag.nl"
  -
    url: "http://library.arjanvandergaag.nl/"
    title:
    text: "My Library"

# The path on the base URL users should be sent to when accessing the feed.
# This gets rewritten to point at your feedburner_url option, which will
# in turn know the location of the real URL.
feed_url: /feed
feedburner_url: http://arjanvandergaag.nl/atom.xml

# Configure the robots.txt file for this site.
# Setting 'default' to true-ish will use sensible defaults. If you
# wish to customize it, you can list paths to allow and to disallow.
# Finally, you could manually set the path to the sitemap file.
#
# You can customize the robots file fairly well like this, but you
# can always manually create a content file with the exact contents
# you need.
robots:
  default: true # disallow assets, allow assets/images and point at sitemap
  # disallow:
  #   - '/tag'
  #   - '/newsletter'
  # allow:
  #   - '/tag/foo'
  # sitemap: '/site-map.txt'

# Set up authentication files for various webmaster tools (or something
# similar). This simply creates a plain text file when generating the site.
#
# identifier: identifier of the output file, e.g. '/google12345/'
# content: content of the file, e.g. 'aoa8202ns001'
# extension: extension of the output file, e.g. 'html' or 'xml'
webmaster_tools:
  -
    identifier: 'google6a204bd2a3818764'
    content:    'google-site-verification: google6a204bd2a3818764.html'
    extension:  'html'

# Set up URL redirects in the .htacccess file to point old URLs to a new
# location, thereby keeping your SEO-mojo intact and visitors happy.
redirects:
  - from: /feed
    to:   http://feeds.feedburner.com/avdgaag
  - from: /code/javascript/2010/02/08/introducing-mutil.html
    to:   http://arjanvandergaag.nl/blog/introducing-mutil.html
  - from: /code/jekyll/2009/06/16/creating-new-jekyll-posts.html
    to:   http://arjanvandergaag.nl/blog/creating-new-jekyll-posts.html
  - from: /code/jekyll/2009/06/13/publishing-a-jekyll-website-to-a-server.html
    to:   http://arjanvandergaag.nl/blog/publishing-a-jekyll-website-to-a-server.html
  - from: /code/jekyll/2009/06/10/rake-task-to-ping-google.html
    to:   http://arjanvandergaag.nl/blog/rake-task-to-ping-google.html
  - from: /code/jekyll/2009/06/07/using-jekyll-to-create-websites.html
    to:   http://arjanvandergaag.nl/blog/using-jekyll-to-create-websites.html
  - from: /meta/2009/06/04/hello-world.html
    to:   http://arjanvandergaag.nl/blog/hello-world.html

# Base URL for the site for use in the XML sitemap
base_url: http://arjanvandergaag.nl

# Whether or not to generate a diff of the compiled content when compiling a
# site. The diff will contain the differences between the compiled content
# before and after the last site compilation.
enable_output_diff: false

# The data sources where nanoc loads its data from. This is an array of
# hashes; each array element represents a single data source. By default,
# there is only a single data source that reads data from the “content/” and
# “layout/” directories in the site directory.
data_sources:
  -
    # The type is the identifier of the data source. By default, this will be
    # `filesystem_unified`.
    type: filesystem_unified

    # The path where items should be mounted (comparable to mount points in
    # Unix-like systems). This is “/” by default, meaning that items will have
    # “/” prefixed to their identifiers. If the items root were “/en/”
    # instead, an item at content/about.html would have an identifier of
    # “/en/about/” instead of just “/about/”.
    items_root: /

    # The path where layouts should be mounted. The layouts root behaves the
    # same as the items root, but applies to layouts rather than items.
    layouts_root: /
