source :rubygems
gem 'nanoc', '~>3.2'
gem 'mime-types'
gem 'fssm'
gem 'rb-fsevent'
gem 'rake'
gem 'coderay'
gem 'nokogiri'
gem 'jsmin'
gem 'kramdown'
gem 'rainpress'
gem 'typogruby'
gem 'jsmin'
gem 'builder'
gem 'rack'
gem 'adsf'
gem 'nanoc-cachebuster'
